services:
  api:
    build: .
    container_name: autoXAK_backend_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --ssl-keyfile /app/key.pem --ssl-certfile /app/cert.pem --reload
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql+asyncpg://autoXAK_user:autoXAK_pass@postgres:5432/autoXAK_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DGIS_USE_MOCK=true
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  postgres:
    image: postgres:16-alpine
    container_name: autoXAK_postgres
    environment:
      POSTGRES_USER: autoXAK_user
      POSTGRES_PASSWORD: autoXAK_pass
      POSTGRES_DB: autoXAK_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U autoXAK_user -d autoXAK_db"]
      interval: 3s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7.2-alpine
    container_name: autoXAK_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
