version: '3.8'

services:
  api:
    build: .
    container_name: autohack_backend_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:7.2-alpine
    container_name: autohack_redis
    ports:
      - "6379:6379"